name: tangani
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  get_storage: 2.0.3
  google_fonts: ^3.0.1
  lottie: 1.3.0
  glassmorphism: 3.0.0
  flutter_svg: ^1.1.1+1
  carousel_slider: 4.1.1
  smooth_page_indicator: 1.0.0+2
  avatar_glow: 2.0.2
  intl: 0.17.0
  permission_handler: ^10.0.0
  image_picker: 0.8.5+3
  flutter_launcher_icons: 0.9.3
  firebase_core: ^1.19.1
  firebase_auth: ^3.4.1
  google_sign_in: 5.3.3
  introduction_screen: 3.0.2
  cloud_firestore: ^3.2.1
  stepper: 0.0.2
  camera: 0.9.8+1
  flutter_facebook_auth: 4.3.4+2
  charts_flutter: 0.12.0
  data_table_2: ^2.3.5
  flutter_clean_calendar: 1.1.0
  dropdown_button2: 1.6.2
  snippet_coder_utils: 1.0.12
  dropdown_search: 5.0.2
  emoji_picker_flutter: 1.3.0
  firebase_storage: 10.3.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.1
  flutter_test: 
    sdk: flutter

flutter_icons: 
  image_path: assets/icons/ico_logo.png
  android: launcher_icon

flutter: 
  assets: 
    - assets/images/
    - assets/avatar/
    - assets/svg/
    - assets/icons/
    - assets/lottie/
    - assets/icons/kategori/
  uses-material-design: true

